######################################################################
# Automatically generated by qmake (2.01a) Thu May 3 22:19:56 2012
######################################################################

TEMPLATE = app
TARGET = motionblur
DEPENDPATH += .
INCLUDEPATH += .

QT += quick qml

# Input
SOURCES += main.cpp
